# Generated by Django 4.0.4 on 2022-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flutterwave_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
